
import React, { useState } from 'react';
import { getBackendFiles, generateSQLSchema, generateHtaccess } from '../services/generatorService';
import { Download, Server, BookOpen, Package, FileText, Folder, ArrowRight, ShieldCheck, Database, Layout, Activity, PlugZap, CheckCircle2, XCircle, Lock, AlertTriangle, RefreshCw } from 'lucide-react';
import JSZip from 'jszip';

export const DeploymentScreen: React.FC = () => {
    
    const [activeTab, setActiveTab] = useState<'guide' | 'architecture' | 'integrity'>('guide');
    const [dbConfig, setDbConfig] = useState({
        host: "localhost",
        name: "u123456789_iitjee",
        user: "u123456789_admin",
        pass: ""
    });
    const [isZipping, setIsZipping] = useState(false);
    const [connectionStatus, setConnectionStatus] = useState<null | 'success' | 'error'>(null);
    const [integrityResults, setIntegrityResults] = useState<any[]>([]);
    const [scanning, setScanning] = useState(false);
    const [repairing, setRepairing] = useState(false);

    // Complete list of all PHP files generated by generatorService.ts
    const API_FILES = [
        'index.php', 'config.php', 'cors.php', 'test_db.php', 'migrate_db.php',
        'login.php', 'register.php', 'google_login.php', 'update_password.php',
        'get_dashboard.php', 'sync_progress.php', 
        'save_attempt.php', 'save_timetable.php',
        'manage_users.php', 'manage_content.php', 'manage_tests.php', 
        'manage_syllabus.php', 'manage_questions.php', 'manage_backlogs.php',
        'manage_goals.php', 'manage_mistakes.php', 'manage_notes.php',
        'manage_videos.php', 'manage_contact.php', 'contact.php',
        'manage_settings.php', 'update_profile.php', 'track_visit.php',
        'get_admin_stats.php', 'search_students.php', 'send_request.php',
        'respond_request.php', 'get_psychometric.php', 'save_psychometric.php',
        'delete_account.php', 'upload_avatar.php'
    ];

    const checkConnection = async () => {
        setConnectionStatus(null);
        try {
            const res = await fetch('/api/test_db.php');
            if (res.ok) {
                const data = await res.json();
                if (data.status === 'CONNECTED') {
                    setConnectionStatus('success');
                    alert(`Success! Connected to DB. ${data.tables.length} tables found.`);
                } else {
                    throw new Error(data.message);
                }
            } else {
                throw new Error(`HTTP ${res.status}`);
            }
        } catch (e: any) {
            setConnectionStatus('error');
            alert(`Connection Failed: ${e.message}. \n\nEnsure your /api folder is uploaded and config.php matches your hosting database.`);
        }
    };

    const runIntegrityScan = async () => {
        setScanning(true);
        setIntegrityResults([]);
        const results = [];

        for (const file of API_FILES) {
            const start = performance.now();
            let status = 'UNKNOWN';
            let code = 0;
            try {
                // Use cache: no-store to avoid browser caching valid responses from previous runs
                const res = await fetch(`/api/${file}`, { method: 'HEAD', cache: 'no-store' }); 
                code = res.status;
                if (res.ok) status = 'OK';
                else if (res.status === 403) status = 'PERM_ERR'; // Permission issue
                else if (res.status === 404) status = 'MISSING';
                else if (res.status === 500) status = 'CRASH'; // DB/Syntax error
                else status = 'ERROR';
            } catch (e) {
                status = 'NET_ERR';
            }
            results.push({ file, status, code, time: Math.round(performance.now() - start) });
            // Sort: Errors first, then Missing, then OK
            results.sort((a, b) => {
                const score = (s: string) => s === 'CRASH' ? 0 : s === 'MISSING' ? 1 : s === 'PERM_ERR' ? 2 : 3;
                return score(a.status) - score(b.status);
            });
            setIntegrityResults([...results]); 
        }
        setScanning(false);
    };

    const runDbRepair = async () => {
        setRepairing(true);
        try {
            const res = await fetch('/api/migrate_db.php');
            if(res.ok) {
                const data = await res.json();
                alert("Database Repair Successful!\n\nAll missing columns have been added. Please try using the app now.");
            } else {
                if (res.status === 404) throw new Error("migrate_db.php not found. Please re-download the bundle.");
                throw new Error(`HTTP ${res.status}`);
            }
        } catch(e: any) {
            alert("Repair Failed: " + e.message);
        } finally {
            setRepairing(false);
        }
    };

    const downloadAllZip = async () => {
        setIsZipping(true);
        try {
            const zip = new JSZip();
            const backendFiles = getBackendFiles(dbConfig);

            // 1. Backend API Files (deployment/api)
            const apiFolder = zip.folder("deployment/api");
            if (apiFolder) {
                backendFiles.filter(f => f.folder === 'deployment/api').forEach(file => {
                    apiFolder.file(file.name, file.content);
                });
            }

            // 2. SEO/Root Files (deployment/seo)
            const seoFolder = zip.folder("deployment/seo");
            if (seoFolder) {
                backendFiles.filter(f => f.folder === 'deployment/seo').forEach(file => {
                    seoFolder.file(file.name, file.content);
                });
                // Add .htaccess for React Router support on Apache
                seoFolder.file(".htaccess", generateHtaccess());
            }

            // 3. SQL (deployment/sql)
            const sqlFolder = zip.folder("deployment/sql");
            if (sqlFolder) {
                sqlFolder.file('database.sql', generateSQLSchema());
            }

            // Generate blob
            const content = await zip.generateAsync({ type: "blob" });
            const url = URL.createObjectURL(content);
            const link = document.createElement('a');
            link.href = url;
            link.download = "iitgeeprep_deployment_bundle.zip";
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        } catch (error) {
            console.error("Failed to zip files", error);
            alert("Error creating zip file.");
        }
        setIsZipping(false);
    };

    return (
        <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 pb-12">
            {/* Header Banner */}
            <div className="bg-gradient-to-r from-slate-800 to-slate-900 rounded-2xl p-8 text-white shadow-xl relative overflow-hidden">
                <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                    <div>
                        <div className="flex items-center gap-3 mb-2">
                            <h2 className="text-3xl font-bold">System Deployment Center</h2>
                            <span className="px-2 py-1 rounded-md bg-slate-700 border border-slate-600 text-xs font-mono text-cyan-400 shadow-sm">
                                v12.21 (Stable)
                            </span>
                        </div>
                        <p className="text-slate-400 text-lg max-w-xl">
                            Download the complete backend kit and verify your server configuration.
                        </p>
                    </div>
                    
                    {/* Tab Switcher */}
                    <div className="flex bg-slate-700/50 p-1 rounded-xl border border-slate-600/50 overflow-x-auto">
                        <button 
                            onClick={() => setActiveTab('guide')}
                            className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap ${
                                activeTab === 'guide' 
                                ? 'bg-blue-600 text-white shadow-lg' 
                                : 'text-slate-400 hover:text-white hover:bg-white/5'
                            }`}
                        >
                            <BookOpen className="w-4 h-4" /> Instructions
                        </button>
                        <button 
                            onClick={() => setActiveTab('integrity')}
                            className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap ${
                                activeTab === 'integrity' 
                                ? 'bg-orange-600 text-white shadow-lg' 
                                : 'text-slate-400 hover:text-white hover:bg-white/5'
                            }`}
                        >
                            <ShieldCheck className="w-4 h-4" /> Integrity Check
                        </button>
                        <button 
                            onClick={() => setActiveTab('architecture')}
                            className={`flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-bold transition-all whitespace-nowrap ${
                                activeTab === 'architecture' 
                                ? 'bg-purple-600 text-white shadow-lg' 
                                : 'text-slate-400 hover:text-white hover:bg-white/5'
                            }`}
                        >
                            <Server className="w-4 h-4" /> Architecture
                        </button>
                    </div>
                </div>
            </div>

            {activeTab === 'integrity' && (
                <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
                    <div className="p-6 border-b border-slate-200 bg-slate-50 flex flex-col md:flex-row justify-between items-center gap-4">
                        <div>
                            <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                                <ShieldCheck className="w-5 h-5 text-orange-600" /> API File Integrity & Permission Scanner
                            </h3>
                            <p className="text-sm text-slate-500">
                                Verify that all {API_FILES.length} backend files exist and have correct permissions (755/644).
                            </p>
                        </div>
                        <div className="flex gap-2">
                            <button 
                                onClick={runDbRepair}
                                disabled={repairing}
                                className="bg-green-600 hover:bg-green-700 text-white px-6 py-2.5 rounded-xl font-bold shadow-md flex items-center gap-2 disabled:opacity-50"
                            >
                                {repairing ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Database className="w-4 h-4" />}
                                {repairing ? 'Repairing...' : 'Auto-Fix Database Schema'}
                            </button>
                            <button 
                                onClick={runIntegrityScan}
                                disabled={scanning}
                                className="bg-orange-600 hover:bg-orange-700 text-white px-6 py-2.5 rounded-xl font-bold shadow-md flex items-center gap-2 disabled:opacity-50"
                            >
                                {scanning ? <Activity className="w-4 h-4 animate-spin" /> : <PlugZap className="w-4 h-4" />}
                                {scanning ? 'Scanning...' : 'Run Diagnostics'}
                            </button>
                        </div>
                    </div>
                    
                    <div className="p-6">
                        {integrityResults.length === 0 ? (
                            <div className="text-center py-12 text-slate-400 bg-slate-50 rounded-xl border border-dashed border-slate-300">
                                <ShieldCheck className="w-12 h-12 mx-auto mb-3 opacity-20" />
                                <p>Click 'Run Diagnostics' to check your server files.</p>
                            </div>
                        ) : (
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                                {integrityResults.map((res: any) => (
                                    <div key={res.file} className={`p-4 rounded-xl border flex items-center justify-between ${
                                        res.status === 'OK' ? 'bg-green-50 border-green-200' :
                                        res.status === 'PERM_ERR' ? 'bg-orange-50 border-orange-200' :
                                        res.status === 'CRASH' ? 'bg-red-50 border-red-200' :
                                        'bg-slate-50 border-slate-200'
                                    }`}>
                                        <div className="flex items-center gap-3">
                                            {res.status === 'OK' && <CheckCircle2 className="w-5 h-5 text-green-600" />}
                                            {res.status === 'MISSING' && <XCircle className="w-5 h-5 text-red-500" />}
                                            {res.status === 'PERM_ERR' && <Lock className="w-5 h-5 text-orange-500" />}
                                            {res.status === 'CRASH' && <AlertTriangle className="w-5 h-5 text-red-600" />}
                                            
                                            <div>
                                                <div className="font-bold text-slate-700 text-sm truncate w-40" title={res.file}>{res.file}</div>
                                                <div className="text-xs font-mono text-slate-500">
                                                    HTTP {res.code} • {res.time}ms
                                                </div>
                                            </div>
                                        </div>
                                        <div className="text-right">
                                            {res.status === 'CRASH' && <span className="text-[10px] font-bold text-red-600 bg-red-100 px-2 py-1 rounded">500 ERROR</span>}
                                            {res.status === 'MISSING' && <span className="text-[10px] font-bold text-red-600 bg-red-100 px-2 py-1 rounded">NOT FOUND</span>}
                                            {res.status === 'PERM_ERR' && <span className="text-[10px] font-bold text-orange-600 bg-orange-100 px-2 py-1 rounded">403 FORBIDDEN</span>}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                        
                        <div className="mt-6 p-4 bg-blue-50 border border-blue-100 rounded-xl text-xs text-blue-800">
                            <strong>Legend:</strong>
                            <ul className="mt-2 list-disc pl-4 space-y-1">
                                <li><strong>200 OK (Green):</strong> File exists and is working correctly.</li>
                                <li><strong>403 Forbidden (Orange):</strong> File exists but permissions are wrong. Set folder to 755 and files to 644.</li>
                                <li><strong>404 Not Found (Red):</strong> File is completely missing from the /api/ folder. Re-upload your deployment bundle.</li>
                                <li><strong>500 Server Error (Red):</strong> File exists but crashed (Likely incorrect Database Credentials in config.php).</li>
                            </ul>
                        </div>
                    </div>
                </div>
            )}

            {activeTab === 'guide' && (
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                    
                    {/* Main Instructions Panel */}
                    <div className="lg:col-span-2 space-y-6">
                        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-sm">
                            <h3 className="text-xl font-bold text-slate-800 mb-6 flex items-center border-b border-slate-100 pb-4">
                                <Package className="w-6 h-6 mr-3 text-blue-600" /> Deployment Workflow
                            </h3>
                            
                            <div className="space-y-8">
                                <div className="flex gap-4">
                                    <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-700 font-bold flex items-center justify-center shrink-0">1</div>
                                    <div>
                                        <h4 className="text-lg font-bold text-slate-800">Download System Bundle</h4>
                                        <p className="text-slate-500 text-sm mt-1 leading-relaxed">
                                            Click the download button on the right. This ZIP contains all necessary server-side files organized into folders (`deployment/api`, `deployment/sql`, `deployment/seo`).
                                        </p>
                                    </div>
                                </div>

                                <div className="flex gap-4">
                                    <div className="w-8 h-8 rounded-full bg-purple-100 text-purple-700 font-bold flex items-center justify-center shrink-0">2</div>
                                    <div>
                                        <h4 className="text-lg font-bold text-slate-800">Build Frontend</h4>
                                        <p className="text-slate-500 text-sm mt-1 leading-relaxed">
                                            Run <code className="bg-slate-100 px-1 py-0.5 rounded text-slate-700 font-mono text-xs">npm run build</code> in your local terminal. 
                                            This creates a <code className="bg-slate-100 px-1 py-0.5 rounded text-slate-700 font-mono text-xs">dist/</code> folder containing the React application.
                                        </p>
                                    </div>
                                </div>

                                <div className="flex gap-4">
                                    <div className="w-8 h-8 rounded-full bg-orange-100 text-orange-700 font-bold flex items-center justify-center shrink-0">3</div>
                                    <div>
                                        <h4 className="text-lg font-bold text-slate-800">Server Mapping</h4>
                                        <p className="text-slate-500 text-sm mt-2 mb-3">Copy files to your server's <code className="font-mono">public_html</code> as follows:</p>
                                        
                                        <div className="bg-slate-50 rounded-xl border border-slate-200 overflow-hidden text-sm">
                                            <div className="grid grid-cols-2 bg-slate-100 p-2 font-bold text-slate-600 border-b border-slate-200">
                                                <div>Source</div>
                                                <div>Destination</div>
                                            </div>
                                            <div className="grid grid-cols-2 p-3 border-b border-slate-100">
                                                <div className="font-mono text-slate-700">dist/*</div>
                                                <div className="font-mono text-blue-600">public_html/</div>
                                            </div>
                                            <div className="grid grid-cols-2 p-3 border-b border-slate-100">
                                                <div className="font-mono text-slate-700">deployment/api/*</div>
                                                <div className="font-mono text-blue-600">public_html/api/</div>
                                            </div>
                                            <div className="grid grid-cols-2 p-3 border-b border-slate-100">
                                                <div className="font-mono text-slate-700">deployment/seo/*</div>
                                                <div className="font-mono text-blue-600">public_html/</div>
                                            </div>
                                            <div className="grid grid-cols-2 p-3 bg-yellow-50/50">
                                                <div className="font-mono text-slate-700">deployment/sql/database.sql</div>
                                                <div className="font-mono text-orange-600">Import via phpMyAdmin</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Sidebar Actions */}
                    <div className="space-y-6">
                        
                        {/* Download Card */}
                        <div className="bg-slate-900 rounded-2xl p-6 text-white shadow-xl relative overflow-hidden">
                            <div className="relative z-10">
                                <h3 className="text-xl font-bold mb-2">Ready to Deploy?</h3>
                                <p className="text-slate-400 text-sm mb-6">Get the full backend kit with SQL schemas and API scripts.</p>
                                
                                <button 
                                    onClick={downloadAllZip} 
                                    disabled={isZipping}
                                    className="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 rounded-xl flex items-center justify-center transition-all shadow-lg active:scale-95 disabled:opacity-50"
                                >
                                    {isZipping ? <Activity className="w-5 h-5 mr-2 animate-spin" /> : <Download className="w-5 h-5 mr-2" />}
                                    Download Bundle .zip
                                </button>
                            </div>
                            <div className="absolute -bottom-10 -right-10 w-32 h-32 bg-blue-500/20 rounded-full blur-2xl"></div>
                        </div>

                        {/* DB Config Form */}
                        <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm">
                            <h4 className="font-bold text-slate-800 mb-4 flex items-center">
                                <Database className="w-4 h-4 mr-2 text-slate-500" /> Pre-Config Database
                            </h4>
                            <p className="text-xs text-slate-500 mb-4">
                                Enter your hosting DB details here to auto-generate the `config.php` inside the bundle.
                            </p>
                            
                            <div className="space-y-3">
                                <div>
                                    <label className="text-[10px] font-bold text-slate-400 uppercase">DB Name</label>
                                    <input 
                                        type="text" 
                                        value={dbConfig.name}
                                        onChange={(e) => setDbConfig({...dbConfig, name: e.target.value})}
                                        className="w-full p-2 border border-slate-200 rounded text-sm mt-1 focus:ring-1 focus:ring-blue-200 outline-none"
                                    />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-slate-400 uppercase">DB User</label>
                                    <input 
                                        type="text" 
                                        value={dbConfig.user}
                                        onChange={(e) => setDbConfig({...dbConfig, user: e.target.value})}
                                        className="w-full p-2 border border-slate-200 rounded text-sm mt-1 focus:ring-1 focus:ring-blue-200 outline-none"
                                    />
                                </div>
                                <div>
                                    <label className="text-[10px] font-bold text-slate-400 uppercase">DB Password</label>
                                    <input 
                                        type="text" 
                                        value={dbConfig.pass}
                                        onChange={(e) => setDbConfig({...dbConfig, pass: e.target.value})}
                                        placeholder="Optional"
                                        className="w-full p-2 border border-slate-200 rounded text-sm mt-1 focus:ring-1 focus:ring-blue-200 outline-none"
                                    />
                                </div>
                            </div>
                        </div>

                        {/* Connection Test Tool */}
                        <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 shadow-sm">
                            <h4 className="font-bold text-slate-800 mb-2 flex items-center">
                                <PlugZap className="w-4 h-4 mr-2 text-slate-500" /> Quick DB Test
                            </h4>
                            <p className="text-xs text-slate-500 mb-4">
                                Use this to check connection AFTER deployment. For file permissions, use the <strong>Integrity Check</strong> tab.
                            </p>
                            <button 
                                onClick={checkConnection}
                                className={`w-full py-2 rounded-lg text-sm font-bold border transition-colors ${
                                    connectionStatus === 'success' ? 'bg-green-100 text-green-700 border-green-200' : 
                                    connectionStatus === 'error' ? 'bg-red-100 text-red-700 border-red-200' : 
                                    'bg-white text-slate-600 border-slate-300 hover:bg-slate-50'
                                }`}
                            >
                                Verify DB Connection
                            </button>
                        </div>

                        <div className="bg-green-50 border border-green-100 p-4 rounded-xl flex items-start gap-3">
                            <ShieldCheck className="w-5 h-5 text-green-600 mt-0.5 shrink-0" />
                            <div className="text-xs text-green-800">
                                <strong className="block mb-1">Security Note</strong>
                                Ensure your `api` folder has 755 permissions. Never upload the source code (`src/`, `package.json`) to the public server.
                            </div>
                        </div>

                    </div>
                </div>
            )}

            {activeTab === 'architecture' && (
                <div className="bg-white p-12 rounded-2xl border border-slate-200 shadow-sm text-center">
                    <Layout className="w-16 h-16 text-slate-200 mx-auto mb-4" />
                    <h3 className="text-xl font-bold text-slate-800 mb-2">System Architecture</h3>
                    <p className="text-slate-500 max-w-lg mx-auto">
                        The IITGEEPrep platform utilizes a decoupled React Frontend (Client-side routing) talking to a lightweight PHP/MySQL Backend via REST API. 
                        State is managed via LocalStorage for offline resilience with sync capabilities.
                    </p>
                </div>
            )}
        </div>
    );
};
